drop table `projects`.`oconim_issue_tags`;
drop table `projects`.`oconim_issue_pictures`;
drop table `projects`.`oconim_issue`;
drop table `projects`.`oconim_picture`;
drop table `projects`.`oconim_place`;
drop table `projects`.`oconim_site`;
drop table `projects`.`oconim_project`;
drop table `projects`.`oconim_user`;
drop table `projects`.`oconim_company`;
